// File generated by FlutterFire CLI (manually recreated)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_aOmXgaOiFY9aFXjFJN7wkKtpBlODY1c',
    appId: '1:1017310577620:web:6db2d61004e5144c958c41',
    messagingSenderId: '1017310577620',
    projectId: 'locatrack-69ca3',
    authDomain: 'locatrack-69ca3.firebaseapp.com',
    databaseURL:
        'https://locatrack-69ca3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locatrack-69ca3.firebasestorage.app',
    measurementId: 'G-BHB7H33ZZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzggZJqfSY4tFghEX8Lzk1ycmBp5284pI',
    appId: '1:1017310577620:android:3ea320c2152fefa4958c41',
    messagingSenderId: '1017310577620',
    projectId: 'locatrack-69ca3',
    storageBucket: 'locatrack-69ca3.firebasestorage.app',
    databaseURL:
        'https://locatrack-69ca3-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
